@startuml "Use Cases"
left to right direction
actor User
actor RegisteredUser
actor OrganizationManager
actor UserManager

rectangle ThingBook {
    rectangle UserManagement {
        usecase Register
        usecase Login
        usecase AssignOrganizationRole
    }

    rectangle OrganizationManagement {
        usecase EstablishOrganization
        usecase CreateSuborganization
    }

    rectangle DataManagement {
        usecase CreateDataSharingTemplate
        usecase EstablishDataSharingAgreement
        usecase PublishCompositeDatastream
    }
}

User                        --> Register
RegisteredUser              --> Login
UserManager                 --> AssignOrganizationRole
OrganizationManager         --> EstablishOrganization
OrganizationManager         --> CreateSuborganization
DataManager                 --> CreateDataSharingTemplate
DataManager                 --> EstablishDataSharingAgreement
PublishCompositeDatastream  <-- ExternalDomain
EstablishOrganization       --> ExternalDomain
@enduml